# .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & start services
        run: |
          docker-compose up -d --build
          # wait for db healthy
          docker-compose exec db sh -c 'until pg_isready -U postgres; do sleep 1; done'

      - name: Install pytest
        run: pip install pytest psycopg2-binary

      - name: Run tests
        run: |
          # inside the web container, or locally pointing at db
          pytest --verbose
