# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & start services
        run: |
          docker compose up -d --build
          # wait for Postgres to be ready
          docker compose exec db sh -c '
            until pg_isready -U postgres > /dev/null 2>&1; do
              echo "Waiting for Postgres…"
              sleep 1
            done
          '

      - name: Wait for Flask API
        # poll the Flask health endpoint or root page until it returns HTTP 200
        run: |
          echo "Waiting for Flask API…"
          until $(curl --silent --fail http://localhost:5000/ > /dev/null); do
            sleep 1
          done
          echo "Flask is up!"

      - name: Tear down
        if: always()
        run: docker compose down -v
